Create ishare2 directory

diff --git a/ishare2 b/ishare2
--- a/ishare2
+++ b/ishare2
@@ -17,6 +17,21 @@ function check_ishare2_dir() {
     fi
     ISHARE2_DIR="/opt/ishare2"
 }
+
+function create_ishare2_dir() {
+    echo -e "${YELLOW}[+] Creating ishare2 directory...${NO_COLOR}"
+    if ! mkdir -p /opt/ishare2 2>/dev/null; then
+        error_message=$(mkdir -p /opt/ishare2 2>&1 >/dev/null)
+        if [[ $error_message == *"Permission denied"* ]]; then
+            echo -e "${RED}[-] Failed to create ishare2 directory: Permission denied.${NO_COLOR}"
+        else
+            echo -e "${RED}[-] Failed to create ishare2 directory.${NO_COLOR}"
+        fi
+        exit 1
+    fi
+    echo -e "${GREEN}[+] Done.${NO_COLOR}"
+}
+
 function set_url_constants() {
     source $ISHARE2_DIR/sources.ishare2
 }
